version: 0.2

phases:
  build:
    commands:
      - mvn clean package
    post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/*.jar
  discard-paths: yes